import { systemWeights } from 'react-native-typography';
export default {
  disabledOpacity: 0.5,
  roundness: 8,
  colors: {
    background: 'rgba(246, 248, 253, 1)',
    darken: 'rgba(0, 0, 0, 0.2)',
    darker_pink: 'rgb(228, 60, 92)',
    divider: 'rgb(230, 231, 244)',
    error: 'rgba(255, 107, 89, 1)',
    golden: 'rgb(252, 216, 109)',
    gray_background: 'rgb(246, 246, 250)',
    light: 'rgba(155, 160, 195, 1)',
    lightInverse: 'rgba(255, 255, 255, 0.68)',
    lighter_pink: 'rgb(255, 110, 139)',
    lightest: 'rgb(217, 219, 236)',
    medium: 'rgba(102, 107, 149, 1)',
    mediumInverse: 'rgba(255, 255, 255, 0.87)',
    primary: 'rgba(252, 82, 115, 1)',
    secondary: 'rgba(122, 210, 206, 1)',
    strong: 'rgba(27, 33, 75, 1)',
    strongInverse: 'rgba(255, 255, 255, 1)',
    surface: 'rgba(255, 255, 255, 1)',
    transparent: 'rgba(255, 255, 255, 0)',
  },
  typography: {
    body1: {
      fontFamily: 'PoppinsRegular',
      fontSize: 15,
      letterSpacing: 0,
      lineHeight: 26,
    },
    body2: {
      fontFamily: 'PoppinsRegular',
      fontSize: 13,
      letterSpacing: 0,
      lineHeight: 22,
    },
    button: {
      fontFamily: 'PoppinsSemiBold',
      fontSize: 15,
      letterSpacing: 0,
      lineHeight: 16,
    },
    caption: {
      ...systemWeights.regular,
      fontSize: 13,
      letterSpacing: 0,
      lineHeight: 16,
    },
    headline1: {
      fontFamily: 'PoppinsSemiBold',
      fontSize: 60,
      letterSpacing: 0,
      lineHeight: 71,
    },
    headline2: {
      fontFamily: 'PoppinsSemiBold',
      fontSize: 48,
      letterSpacing: 0,
      lineHeight: 58,
    },
    headline3: {
      fontFamily: 'PoppinsSemiBold',
      fontSize: 40,
      letterSpacing: 0,
      lineHeight: 46,
    },
    headline4: {
      fontFamily: 'PoppinsSemiBold',
      fontSize: 24,
      letterSpacing: 0,
      lineHeight: 46,
    },
    headline5: {
      fontFamily: 'PoppinsSemiBold',
      fontSize: 20,
      letterSpacing: 0,
      lineHeight: 26,
    },
    headline6: {
      fontFamily: 'PoppinsSemiBold',
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 20,
    },
    overline: {
      fontFamily: 'PoppinsMedium',
      fontSize: 12,
      letterSpacing: 2,
      lineHeight: 16,
    },
    subtitle1: {
      fontFamily: 'PoppinsRegular',
      fontSize: 15,
      letterSpacing: 0,
      lineHeight: 26,
    },
    subtitle2: {
      ...systemWeights.regular,
      fontSize: 13,
      letterSpacing: 0,
      lineHeight: 22,
    },
    custom14: {
      fontFamily: 'PoppinsSemiBold',
      fontSize: 24,
      letterSpacing: 0,
      lineHeight: 36,
    },
    custom15: {
      fontFamily: 'PoppinsSemiBold',
      fontSize: 24,
      letterSpacing: 0,
      lineHeight: 36,
    },
    custom16: {
      fontFamily: 'WorkSansRegular',
      fontSize: 24,
      letterSpacing: 0,
      lineHeight: 46,
    },
    custom17: {
      fontFamily: 'MerriweatherRegularItalic',
      fontSize: 24,
      letterSpacing: 0,
      lineHeight: 46,
    },
    custom18: {
      fontFamily: 'MerriweatherBoldItalic',
      fontSize: 24,
      letterSpacing: 0,
      lineHeight: 46,
    },
    custom19: {
      fontFamily: 'PoppinsSemiBold',
      fontSize: 24,
      letterSpacing: 0,
      lineHeight: 46,
    },
    custom20: {
      fontFamily: 'PoppinsSemiBold',
      fontSize: 24,
      letterSpacing: 0,
      lineHeight: 46,
    },
    custom21: {
      fontFamily: 'PoppinsSemiBold',
      fontSize: 26,
      letterSpacing: 0,
      lineHeight: 46,
    },
    custom22: {
      fontFamily: 'PoppinsSemiBold',
      fontSize: 24,
      letterSpacing: 0,
      lineHeight: 46,
    },
    custom23: {
      fontFamily: 'PoppinsBold',
      fontSize: 24,
      letterSpacing: 0,
      lineHeight: 46,
    },
    custom24: {
      fontFamily: 'PoppinsBold',
      fontSize: 24,
      letterSpacing: 0,
      lineHeight: 46,
    },
    custom25: {
      fontFamily: 'PoppinsMedium',
      fontSize: 13,
      letterSpacing: 0,
      lineHeight: 22,
    },
    custom26: {
      ...systemWeights.regular,
      fontSize: 13,
      letterSpacing: 0,
      lineHeight: 16,
    },
    custom27: {
      ...systemWeights.regular,
      fontSize: 13,
      letterSpacing: 0,
      lineHeight: 16,
    },
    custom28: {
      fontFamily: 'PoppinsSemiBold',
      fontSize: 24,
      letterSpacing: 0,
      lineHeight: 32,
    },
    custom29: {
      fontFamily: 'PoppinsSemiBold',
      fontSize: 24,
      letterSpacing: 0,
      lineHeight: 32,
    },
    custom30: {
      fontFamily: 'PoppinsSemiBold',
      fontSize: 24,
      letterSpacing: 0,
      lineHeight: 24,
    },
    custom31: {
      fontFamily: 'PoppinsSemiBold',
      fontSize: 24,
      letterSpacing: 0,
      lineHeight: 48,
    },
    custom32: {
      fontFamily: 'PoppinsSemiBold',
      fontSize: 24,
      letterSpacing: 0,
      lineHeight: 48,
    },
    custom33: {
      fontFamily: 'PoppinsSemiBold',
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom34: {
      fontFamily: 'PoppinsSemiBold',
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom35: {
      fontFamily: 'PoppinsSemiBold',
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom36: {
      fontFamily: 'PoppinsSemiBold',
      fontSize: 24,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom37: {
      fontFamily: 'PoppinsSemiBold',
      fontSize: 24,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom38: {
      fontFamily: 'PoppinsSemiBold',
      fontSize: 24,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom39: {
      fontFamily: 'PoppinsSemiBold',
      fontSize: 24,
      letterSpacing: 1,
      lineHeight: 16,
    },
  },
};
